export interface EmployeeData {
  id: number;
  firstName: string;
  lastName: string;
  image: string;
  sex: string;
  password: string;
  salary: number;
  role: string;
  phone: string;
  birthDate: string;
  username: string;
}

export const employees: EmployeeData[] = [
  {
    id: 1,
    firstName: "Ava",
    lastName: "Moore",
    image: "https://example.com/images/ava.jpg",
    sex: "Female",
    password: "password123",
    salary: 45000,
    role: "Manager",
    phone: "123-456-7891",
    birthDate: "1990-01-01",
    username: "ava.moore",
  },
  {
    id: 2,
    firstName: "Ethan",
    lastName: "Clark",
    image: "https://example.com/images/ethan.jpg",
    sex: "Male",
    password: "password123",
    salary: 38000,
    role: "Receptionist",
    phone: "234-567-8902",
    birthDate: "1985-02-02",
    username: "ethan.clark",
  },
  {
    id: 3,
    firstName: "Sophia",
    lastName: "Johnson",
    image: "https://example.com/images/sophia.jpg",
    sex: "Female",
    password: "password123",
    salary: 42000,
    role: "Chef",
    phone: "345-678-9012",
    birthDate: "1992-03-03",
    username: "sophia.johnson",
  },
  {
    id: 4,
    firstName: "Liam",
    lastName: "Brown",
    image: "https://example.com/images/liam.jpg",
    sex: "Male",
    password: "password123",
    salary: 40000,
    role: "Housekeeper",
    phone: "456-789-0123",
    birthDate: "1988-04-04",
    username: "liam.brown",
  },
  {
    id: 5,
    firstName: "Olivia",
    lastName: "Davis",
    image: "https://example.com/images/olivia.jpg",
    sex: "Female",
    password: "password123",
    salary: 47000,
    role: "Manager",
    phone: "567-890-1234",
    birthDate: "1991-05-05",
    username: "olivia.davis",
  },
  {
    id: 6,
    firstName: "Noah",
    lastName: "Miller",
    image: "https://example.com/images/noah.jpg",
    sex: "Male",
    password: "password123",
    salary: 39000,
    role: "Receptionist",
    phone: "678-901-2345",
    birthDate: "1987-06-06",
    username: "noah.miller",
  },
  {
    id: 7,
    firstName: "Isabella",
    lastName: "Wilson",
    image: "https://example.com/images/isabella.jpg",
    sex: "Female",
    password: "password123",
    salary: 43000,
    role: "Chef",
    phone: "789-012-3456",
    birthDate: "1993-07-07",
    username: "isabella.wilson",
  },
  {
    id: 8,
    firstName: "James",
    lastName: "Moore",
    image: "https://example.com/images/james.jpg",
    sex: "Male",
    password: "password123",
    salary: 41000,
    role: "Housekeeper",
    phone: "890-123-4567",
    birthDate: "1989-08-08",
    username: "james.moore",
  },
  {
    id: 9,
    firstName: "Mia",
    lastName: "Taylor",
    image: "https://example.com/images/mia.jpg",
    sex: "Female",
    password: "password123",
    salary: 46000,
    role: "Manager",
    phone: "901-234-5678",
    birthDate: "1994-09-09",
    username: "mia.taylor",
  },
  {
    id: 10,
    firstName: "Lucas",
    lastName: "Anderson",
    image: "https://example.com/images/lucas.jpg",
    sex: "Male",
    password: "password123",
    salary: 37000,
    role: "Receptionist",
    phone: "012-345-6789",
    birthDate: "1986-10-10",
    username: "lucas.anderson",
  },
];
